language: python
python:
    - "2.6"
    - "2.7"
install:
    - "pip install ."
    - "pip install -r requirements-dev.txt"
script:
  - "flake8 netflix_roulette/netflix_roulette_api.py"
  - "py.test tests/simple.py"
