language: python
python:
    - "2.6"
    - "2.7"
install:
    - "pip install ."
    - "pip install -r requirements-dev.txt"
script:
  - "flake8 --exclude=__init__.py netflix_roulette"
  - "py.test tests/media.py tests/person.py"
