language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
install:
    - "pip install -r requirements.txt"
    - "pip install ."
script:
  - "flake8 --exclude=__init__.py netflix_roulette"
  - "py.test tests/media.py tests/person.py"
